[tools]
go = "1.24"
bun = "latest"

[tasks.backend_deps]
run = "go mod download"
dir = "backend"
description = "バックエンド依存関係を取得"

[tasks.backend_dev]
run = "go run ./cmd/server"
dir = "backend"
description = "バックエンドAPIサーバーを起動"

[tasks.backend_test]
run = "go test ./..."
dir = "backend"
description = "バックエンドのGoテストを実行"

[tasks.frontend_install]
run = "bun install"
dir = "frontend"
description = "フロントエンド依存関係をインストール"




[tasks.frontend_dev]
run = "bun run dev"
dir = "frontend"
description = "Next.js開発サーバー"

[tasks.frontend_build]
run = "bun run build"
dir = "frontend"
description = "Next.jsアプリのビルド"

[tasks.frontend_lint]
run = "bun run lint"
dir = "frontend"
description = "フロントエンドLint"

[tasks.frontend_lint_fix]
run = "bun run lint:fix"
dir = "frontend"
description = "フロントエンドLintの自動修正"

[tasks.setup]
depends = ["backend_deps", "frontend_install"]
description = "モノレポ環境の初期セットアップ"

[tasks.dev]
run = "bun run dev:all"
description = "バックエンドとフロントエンドの開発サーバーを並列起動するユーティリティ"

[tasks.test]
depends = ["backend_test"]
description = "全体テスト（現状はバックエンドのみ）"

