[tools]
bun = "latest"

[tasks.backend_deps]
run = "bun install --force"
dir = "backend"
description = "バックエンド依存関係をインストール"
wait_for = ["shared_deps"]

[tasks.backend_dev]
run = "bun run dev"
dir = "backend"
description = "バックエンドAPIサーバーを起動"

[tasks.dev]
depends = ["backend_dev", "frontend_dev"]
description = "バックエンドとフロントエンドの開発サーバーを起動"

[tasks.backend_typecheck]
run = "bun run typecheck"
dir = "backend"
description = "バックエンドのTypeScript型チェックを実行"

[tasks.backend_lint]
run = "bun run lint"
dir = "backend"
description = "バックエンドのコードをリント"

[tasks.frontend_install]
run = "bun install --force"
dir = "frontend"
description = "フロントエンド依存関係をインストール"
wait_for = ["shared_deps", "backend_deps"]

[tasks.frontend_dev]
run = "bun run dev"
dir = "frontend"
description = "フロントエンド開発サーバー"

[tasks.frontend_build]
run = "bun run build"
dir = "frontend"
description = "フロントエンドのビルド"

[tasks.frontend_lint]
run = "bun run lint"
dir = "frontend"
description = "フロントエンドの lint"

[tasks.frontend_lint_fix]
run = "bun run lint:fix"
dir = "frontend"
description = "フロントエンドの lint を自動修正"

[tasks.setup]
depends = ["shared_deps", "backend_frontend_deps"]
description = "モノレポ環境の初期セットアップ"

[tasks.shared_deps]
run = "bun install --force"
dir = "shared"
description = "共有パッケージ依存関係をインストール"

[tasks.backend_frontend_deps]
depends = ["backend_deps", "frontend_install"]
description = "バックエンドとフロントエンドの依存関係をインストール"
wait_for = ["shared_deps"]

[tasks.dev_background]
run = "bun run dev"
description = "バックグラウンドで開発サーバーを起動"

[tasks.lint]
depends = ["backend_lint", "frontend_lint"]
description = "バックエンドとフロントエンドのリントを実行"

[tasks.typecheck]
depends = ["backend_typecheck"]
description = "バックエンドの型チェックを実行"

