[tools]
go = "1.24"
bun = "latest"

[tasks.backend_deps]
run = "go mod download"
dir = "backend"
description = "バックエンド依存関係を取得"

[tasks.backend_dev]
run = "go run ./cmd/server"
dir = "backend"
description = "バックエンドAPIサーバーを起動"

[tasks.backend_test]
run = "go test ./..."
dir = "backend"
description = "バックエンドのGoテストを実行"

[tasks.backend_fmt]
run = "gofmt -w internal"
dir = "backend"
description = "バックエンドのGoコードを整形"

[tasks.frontend_install]
run = "bun install"
dir = "frontend"
description = "フロントエンド依存関係をインストール"

[tasks.frontend_dev]
run = "bun run dev"
dir = "frontend"
description = "フロントエンド開発サーバー"

[tasks.frontend_build]
run = "bun run build"
dir = "frontend"
description = "フロントエンドのビルド"

[tasks.frontend_lint]
run = "bun run lint"
dir = "frontend"
description = "フロントエンドの lint"

[tasks.frontend_lint_fix]
run = "bun run lint:fix"
dir = "frontend"
description = "フロントエンドの lint を自動修正"

[tasks.setup]
depends = ["backend_deps", "frontend_install"]
description = "モノレポ環境の初期セットアップ"

[tasks.dev]
depends = ["backend_dev", "frontend_dev"]
description = "バックエンドとフロントエンドの開発サーバーを起動"

