# 通知送信 - リトライなしバージョン
name: Daily Medication Notification

on:
  schedule:
    - cron: '50 12 * * *'
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST https://okusuri-backend.onrender.com/api/notification)
          http_code=$(echo "$response" | tail -n1)

          if [ "$http_code" -eq 200 ]; then
            echo "Notification sent successfully"
            exit 0
          else
            echo "Notification failed with status $http_code"
            exit 1
          fi
