name: renotate

on:
  # スケジュール実行（毎日午前2時）
  schedule:
    - cron: '0 2 * * *'
  
  # 手動実行
  workflow_dispatch:
    inputs:
      package_manager:
        description: '更新するパッケージマネージャー'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - npm
          - go

  # プッシュ時の実行（設定ファイル変更時）
  push:
    paths:
      - 'renotate.yml'
      - '.github/workflows/renotate.yml'

jobs:
  renotate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      checks: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: backend/go.sum
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Configure Git
        run: |
          git config --global user.name "renotate[bot]"
          git config --global user.email "renotate[bot]@users.noreply.github.com"
      
      - name: Check for updates
        id: check-updates
        run: |
          # フロントエンドの依存関係をチェック
          if [ "${{ github.event.inputs.package_manager }}" = "all" ] || [ "${{ github.event.inputs.package_manager }}" = "npm" ]; then
            echo "Checking frontend dependencies..."
            cd frontend
            bun install
            bun outdated --json > ../frontend-outdated.json || true
            cd ..
          fi
          
          # バックエンドの依存関係をチェック
          if [ "${{ github.event.inputs.package_manager }}" = "all" ] || [ "${{ github.event.inputs.package_manager }}" = "go" ]; then
            echo "Checking backend dependencies..."
            cd backend
            go list -u -m all > ../go-outdated.txt || true
            cd ..
          fi
      
      - name: Run renotate
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        run: |
          # renotateスクリプトを実行
          npm run renotate
      
      - name: Run tests
        if: github.event_name == 'pull_request'
        run: |
          # フロントエンドのテスト
          cd frontend
          bun run lint
          bun run build
          cd ..
          
          # バックエンドのテスト
          cd backend
          go test ./...
          cd ..