name: Renovate

on:
  # スケジュール実行（毎週月曜日午前2時）
  schedule:
    - cron: '0 2 * * 1'
  
  # 手動実行
  workflow_dispatch:
    inputs:
      package_manager:
        description: '更新するパッケージマネージャー'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - npm
          - go

  # プッシュ時の実行（設定ファイル変更時）
  push:
    paths:
      - 'renovate.json'
      - '.github/workflows/renovate.yml'

jobs:
  renovate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      issues: write
      checks: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: backend/go.sum
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Configure Git
        run: |
          git config --global user.name "renovate[bot]"
          git config --global user.email "renovate[bot]@users.noreply.github.com"
      
      - name: Run Renovate
        uses: renovatebot/github-action@v40
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run tests
        if: github.event_name == 'pull_request'
        run: |
          # フロントエンドのテスト
          cd frontend
          bun run lint
          bun run build
          cd ..
          
          # バックエンドのテスト
          cd backend
          go test ./...
          cd ..